### PR TITLE
aiohttp-cors

### PR DESCRIPTION
**Pull request by roadscape**
issue #53

### CODE REVIEW

**Comment by sneak** [comment]
Vetoing this change - no clients should speak directly to `hivemind`, only via `jussi`. `jussi` is a required dependency for correct `hivemind` operation anyway.

**Comment by roadscape** [comment]
jussi is optional but it does help a lot unless you're using a local node.

**Comment by sneak** [comment]
No, because making api calls via our libraries/sdk uses only one endpoint for calls to steemd and to hivemind.  Maybe in the future all reads go to hivemind and all writes go via steemconnect, but today our libraries are instantiated with a single endpoint that is expected to do multiplexing.

**Comment by roadscape** [comment]
My point is right now everything works without jussi; it's a requirement for testing. We can hardcode jussi dependency for release, this is simple.

Personally, I'd rather not make soft dependencies hard.

**Comment by roadscape** [comment]
(Just to clarify, I agree hive doesn't need CORS support rn.)

**Pull request closed without merging**
